name: Deploy MultiK8s
on:
  push:
    branches:
      - main
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t mezgebre/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true mezgebre/react-test npm test
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-358422
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c
 
      - name: Build
        run: |-
          docker build -t mezgebre/multi-client:latest -t mezgebre/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t mezgebre/multi-server:latest -t mezgebre/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t mezgebre/multi-worker:latest -t mezgebre/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push mezgebre/multi-client:latest
          docker push mezgebre/multi-server:latest
          docker push mezgebre/multi-worker:latest
 
          docker push mezgebre/multi-client:${{ env.SHA }}
          docker push mezgebre/multi-server:${{ env.SHA }}
          docker push mezgebre/multi-worker:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-depl server=mezgebre/multi-server:${{ env.SHA }}
          kubectl set image deployments/client-depl client=mezgebre/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-depl worker=mezgebre/multi-worker:${{ env.SHA }}